-- Inserção de dados com categorias e tipos
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Nissan Kicks', TRUE, 'Nissan', 2023, 'ABC1D23', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Chevrolet Tracker', TRUE, 'Chevrolet', 2023, 'DEF2G34', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Fiat Argo', FALSE, 'Fiat', 2023, 'GHI3H45', 'C', 'Hatch');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Toyota Yaris', TRUE, 'Toyota', 2023, 'JKL4I56', 'C', 'Hatch');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Honda HR-V', TRUE, 'Honda', 2024, 'MNO5J67', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Hyundai Creta', TRUE, 'Hyundai', 2023, 'PQR6K78', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Jeep Compass', FALSE, 'Jeep', 2023, 'STU7L89', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Renault Duster', TRUE, 'Renault', 2024, 'VWX8M90', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Volkswagen Taos', TRUE, 'Volkswagen', 2023, 'YZA9N01', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Ford Territory', FALSE, 'Ford', 2023, 'BCD0O12', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Peugeot 3008', TRUE, 'Peugeot', 2024, 'CDE1P23', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Audi Q3', TRUE, 'Audi', 2024, 'DEF2Q34', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('BMW X1', TRUE, 'BMW', 2024, 'FGH3R45', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Kia Seltos', TRUE, 'Kia', 2023, 'GHI4S56', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Chery Tiggo 2 Pro', TRUE, 'Chery', 2023, 'HIJ5T67', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Citroën C3', FALSE, 'Citroën', 2023, 'IJK6U78', 'C', 'Hatch');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Chevrolet Onix', TRUE, 'Chevrolet', 2024, 'JKL7V89', 'C', 'Hatch');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Fiat Mobi', TRUE, 'Fiat', 2024, 'KLM8W90', 'D', 'Hatch');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Toyota Corolla', TRUE, 'Toyota', 2023, 'LMN9X01', 'B', 'Sedan');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Honda Civic', FALSE, 'Honda', 2024, 'MNO0Y12', 'C', 'Sedan');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Hyundai HB20', TRUE, 'Hyundai', 2023, 'NOP1Z23', 'C', 'Hatch');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Jeep Renegade', TRUE, 'Jeep', 2023, 'OPQ2A34', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Renault Kwid', TRUE, 'Renault', 2023, 'PQR3B45', 'D', 'Hatch');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Volkswagen Polo', TRUE, 'Volkswagen', 2024, 'QRS4C56', 'C', 'Hatch');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Ford EcoSport', FALSE, 'Ford', 2024, 'RST5D67', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Peugeot 208', TRUE, 'Peugeot', 2023, 'STU6E78', 'C', 'Hatch');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Audi A3', TRUE, 'Audi', 2024, 'TUV7F89', 'C', 'Sedan');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('BMW 320i', TRUE, 'BMW', 2023, 'UVW8G90', 'B', 'Sedan');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Kia Picanto', FALSE, 'Kia', 2023, 'WXY9H01', 'D', 'Hatch');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Chery Tiggo 5X', TRUE, 'Chery', 2024, 'XYZ0I12', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Citroën C4 Cactus', TRUE, 'Citroën', 2023, 'ZAB1J23', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Chevrolet Tracker Premier', TRUE, 'Chevrolet', 2024, 'BCD2K34', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Fiat Pulse', TRUE, 'Fiat', 2024, 'CDE3L45', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Toyota SW4', TRUE, 'Toyota', 2023, 'DEF4M56', 'A', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Honda WR-V', TRUE, 'Honda', 2024, 'EFG5N67', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Hyundai Tucson', FALSE, 'Hyundai', 2023, 'FGH6O78', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Jeep Gladiator', TRUE, 'Jeep', 2024, 'GHI7P89', 'A', 'Picape');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Renault Oroch', TRUE, 'Renault', 2023, 'HIJ8Q90', 'B', 'Picape');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Volkswagen Virtus', TRUE, 'Volkswagen', 2024, 'IJK9R01', 'C', 'Sedan');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Ford Ranger', TRUE, 'Ford', 2023, 'JKL0S12', 'A', 'Picape');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Peugeot 5008', TRUE, 'Peugeot', 2024, 'KLM1T23', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Audi Q5', TRUE, 'Audi', 2023, 'LMN2U34', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('BMW X3', TRUE, 'BMW', 2023, 'MNO3V45', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Kia Sorento', FALSE, 'Kia', 2024, 'NOP4W56', 'B', 'SUV');
INSERT INTO car (model, available, brand, year_model, license_plate, category, type) VALUES ('Chery Tiggo 7 Pro', TRUE, 'Chery', 2024, 'OPQ5X67', 'B', 'SUV');
